version: '3'

services:
  gateway:
    image: jinsungguri/fanup-gateway:latest
    ports:
      - '3000:3000'
    networks:
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  auth:
    image: jinsungguri/fanup-auth:latest
    ports:
      - '3001:3001'
      - '4001:4001'
    networks:
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  core:
    image: jinsungguri/fanup-core:latest
    ports:
      - '3002:3002'
      - '4002:4002'
    networks:
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  ticket:
    image: jinsungguri/fanup-ticket:latest
    ports:
      - '3003:3003'
      - '4003:4003'
    networks:
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  backend:
    driver: bridge
