name: SERVER-DEPLOY

on:
  push:
    branches: [Feat/#13-deploy]
  pull_request:
    branches: [Feat/#13-deploy]

jobs:
  build:
    name: Deploy MSA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./server"
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./gateway/Dockerfile
            image: jinsungguri/FanUP-gateway:latest
          - dockerfile: ./services/auth/Dockerfile
            image: jinsungguri/FanUP-auth:latest
          - dockerfile: ./services/api/Dockerfile
            image: jinsungguri/FanUP-api:latest
          - dockerfile: ./services/ticket/Dockerfile
            image: jinsungguri/FanUP-ticket:latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.args.DOCKER_META_IMAGES }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          run: |
