name: TEST-COVERAGE

on:
  push:
    branches:
      - "Feat/#20-fanup-socket"
  # pull_request:
  #   branches:
  #     - main
  #     - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Nest.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Node_modules
        run: |
          cd ./client
          npm install
          cd ..
          cd ./server/gateway
          npm ci
          cd ../services/core
          npm ci
          cd ../auth
          npm ci
          cd ../ticket
          npm ci

      - name: Run Test Coverage
        run: |
          npm ci
          npm run coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
